import type { ServiceType } from '@/types/saju';

export const SERVICE_NAMES: Record<ServiceType, string> = {
  comprehensive: '종합 사주 풀이',
  compatibility: '궁합 분석',
  daeun: '대운 분석',
  yearly: '올해의 운세',
  daily: '오늘의 운세',
  chat: 'AI 상담',
  business: '사업운',
  luckyday: '길일 택일',
  love: '연애운',
  wealth: '재물운',
  health: '건강운',
  career: '직업운',
  pastlife: '전생 분석',
  moving: '이사운',
  mbti: '사주 MBTI',
  pet: '반려동물 궁합',
  travel: '여행운',
  food: '식복 분석',
  color: '퍼스널 컬러',
  study: '학업운',
  ancestor: '조상운',
  child: '자녀운',
  secret: '숨겨진 재능',
  timing: '타이밍 분석',
};

export const SERVICE_EMOJIS: Record<ServiceType, string> = {
  comprehensive: '🔮',
  compatibility: '💕',
  daeun: '🌊',
  yearly: '📅',
  daily: '☀️',
  chat: '💬',
  business: '💼',
  luckyday: '📆',
  love: '❤️',
  wealth: '💰',
  health: '🏥',
  career: '👔',
  pastlife: '🌀',
  moving: '🏠',
  mbti: '🧬',
  pet: '🐾',
  travel: '✈️',
  food: '🍽️',
  color: '🎨',
  study: '📚',
  ancestor: '🏛️',
  child: '👶',
  secret: '🌟',
  timing: '⏰',
};
